Repository RogeanCosta/SendMe, pull requests merged in 2019-12, with the labels that each got.

#47 Atualizando SM - 10
  Aplicativo/front-end/app-react/src/components/Login/index.js
  Aplicativo/front-end/app-react/src/components/tela-cadastro/index.js
Labels: duplicate

#46 Sm 18
  Aplicativo/front-end/app-react/src/components/App/index.js
  Aplicativo/front-end/app-react/src/components/Menu/index.js
  Aplicativo/front-end/app-react/src/components/Menu/menu.css
  Aplicativo/front-end/app-react/src/components/TelaInicial/index.js
Labels: enhancement

#52 Tela de Carrinho
  Aplicativo/front-end/app-react/src/components/App/index.js
  Aplicativo/front-end/app-react/src/components/Carrinho/index.css
  Aplicativo/front-end/app-react/src/components/Carrinho/index.js
Labels: enhancement

#53 recuperar senha integrada com firebase
  Aplicativo/front-end/app-react/src/components/Menu/index.js
  Aplicativo/front-end/app-react/src/components/Menu/menu.css
  Aplicativo/front-end/app-react/src/components/RecuperarSenha/index.js
  Aplicativo/front-end/app-react/src/components/TelaInicial/index.js
Labels: enhancement

#65 modificações na posição das caixas de texto
  Aplicativo/front-end/app-react/src/components/Pagamentos/index.css
  Aplicativo/front-end/app-react/src/components/Pagamentos/index.js
Labels: bug
